# Generated by Django 5.1.1 on 2024-08-27 01:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('60'))])),
                ('temperature_feels_like', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('60'))])),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in kilometers per hour', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wind_direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'Northeast'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('NW', 'Northwest')], max_length=2)),
                ('pressure', models.DecimalField(decimal_places=2, help_text='Pressure in millibars', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('870')), django.core.validators.MaxValueValidator(Decimal('1080'))])),
                ('precipitation', models.DecimalField(decimal_places=2, help_text='Precipitation in millimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('dewpoint', models.DecimalField(decimal_places=2, help_text='Dewpoint in Celsius', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('60'))])),
                ('uv_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('gust_speed', models.DecimalField(decimal_places=2, help_text='Gust in kilometers per hour', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('visibility', models.DecimalField(decimal_places=2, help_text='Visibility in kilometers', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('record_timestamp', models.DateTimeField(help_text='Time in UTC')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', '-record_timestamp'], name='weather_loc_name_289acd_idx')],
            },
        ),
    ]
