# Generated by Django 5.1.1 on 2024-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationweather',
            name='condition',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='locationweather',
            name='condition_icon',
            field=models.URLField(blank=True),
        ),
    ]
